<?php

namespace Shop\BackendBundle\Repository;

/**
 * EventStoreRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventStoreRowRepository extends \Doctrine\ORM\EntityRepository
{
}
